from . import res_users
from . import purchase_order
from . import account_move
from . import stock_picking
from . import sale_order
from . import stock_rule
from . import pod_reason
from . import hr_attendance
from . import hr_leave_allocation